event_tmpls = {
    'pull_request_event': {'id': "event_data['id']", 'type': "event_data['type']",
                           'created_at': "event_data['created_at']", 'actor__id': "event_data['actor']['id']",
                           'actor__login': "event_data['actor']['login']",
                           'actor__display_login': "event_data['actor']['display_login']",
                           'repo__id': "event_data['repo']['id']", 'repo__name': "event_data['repo']['name']",
                           'payload__action': "event_data['payload']['action']",
                           'payload__number': "event_data['payload']['number']",
                           'payload__pull_request__id': "event_data['payload']['pull_request']['id']",
                           'payload__pull_request__node_id': "event_data['payload']['pull_request']['node_id']",
                           'payload__pull_request__number': "event_data['payload']['pull_request']['number']",
                           'payload__pull_request__state': "event_data['payload']['pull_request']['state']",
                           'payload__pull_request__title': "event_data['payload']['pull_request']['title']",
                           'payload__pull_request__user__login': "event_data['payload']['pull_request']['user']['login']",
                           'payload__pull_request__user__id': "event_data['payload']['pull_request']['user']['id']",
                           'payload__pull_request__user__node_id': "event_data['payload']['pull_request']['user']['node_id']",
                           'payload__pull_request__user__type': "event_data['payload']['pull_request']['user']['type']",
                           'payload__pull_request__created_at': "event_data['payload']['pull_request']['created_at']",
                           'payload__pull_request__updated_at': "event_data['payload']['pull_request']['updated_at']",
                           'payload__pull_request__base__repo__fork': "event_data['payload']['pull_request']['base']['repo']['fork']",
                           'payload__pull_request__merged': "event_data['payload']['pull_request']['merged']",
                           'payload__pull_request__body': "event_data['payload']['pull_request']['body']",
                           'payload__pull_request__merge_commit_sha': "event_data['payload']['pull_request']['merge_commit_sha']",
                           'payload__pull_request__head__repo__private': "event_data['payload']['pull_request']['head']['repo']['private']",
                           'payload__pull_request__head__repo__fork': "event_data['payload']['pull_request']['head']['repo']['fork']",
                           'payload__pull_request__base__repo__private': "event_data['payload']['pull_request']['base']['repo']['private']",
                           'payload__pull_request__closed_at': "event_data['payload']['pull_request']['closed_at']",
                           'payload__pull_request__merged_at': "event_data['payload']['pull_request']['merged_at']",
                           'payload__pull_request__head__label': "event_data['payload']['pull_request']['head']['label']",
                           'payload__pull_request__head__ref': "event_data['payload']['pull_request']['head']['ref']",
                           'payload__pull_request__head__sha': "event_data['payload']['pull_request']['head']['sha']",
                           'payload__pull_request__head__user__login': "event_data['payload']['pull_request']['head']['user']['login']",
                           'payload__pull_request__head__user__id': "event_data['payload']['pull_request']['head']['user']['id']",
                           'payload__pull_request__head__user__node_id': "event_data['payload']['pull_request']['head']['user']['node_id']",
                           'payload__pull_request__head__user__type': "event_data['payload']['pull_request']['head']['user']['type']",
                           'payload__pull_request__head__repo__id': "event_data['payload']['pull_request']['head']['repo']['id']",
                           'payload__pull_request__head__repo__node_id': "event_data['payload']['pull_request']['head']['repo']['node_id']",
                           'payload__pull_request__head__repo__name': "event_data['payload']['pull_request']['head']['repo']['name']",
                           'payload__pull_request__head__repo__full_name': "event_data['payload']['pull_request']['head']['repo']['full_name']",
                           'payload__pull_request__head__repo__owner__login': "event_data['payload']['pull_request']['head']['repo']['owner']['login']",
                           'payload__pull_request__head__repo__owner__id': "event_data['payload']['pull_request']['head']['repo']['owner']['id']",
                           'payload__pull_request__head__repo__owner__node_id': "event_data['payload']['pull_request']['head']['repo']['owner']['node_id']",
                           'payload__pull_request__head__repo__owner__type': "event_data['payload']['pull_request']['head']['repo']['owner']['type']",
                           'payload__pull_request__head__repo__description': "event_data['payload']['pull_request']['head']['repo']['description']",
                           'payload__pull_request__head__repo__created_at': "event_data['payload']['pull_request']['head']['repo']['created_at']",
                           'payload__pull_request__head__repo__updated_at': "event_data['payload']['pull_request']['head']['repo']['updated_at']",
                           'payload__pull_request__head__repo__pushed_at': "event_data['payload']['pull_request']['head']['repo']['pushed_at']",
                           'payload__pull_request__head__repo__language': "event_data['payload']['pull_request']['head']['repo']['language']",
                           'payload__pull_request__head__repo__default_branch': "event_data['payload']['pull_request']['head']['repo']['default_branch']",
                           'payload__pull_request__base__label': "event_data['payload']['pull_request']['base']['label']",
                           'payload__pull_request__base__ref': "event_data['payload']['pull_request']['base']['ref']",
                           'payload__pull_request__base__sha': "event_data['payload']['pull_request']['base']['sha']",
                           'payload__pull_request__base__user__login': "event_data['payload']['pull_request']['base']['user']['login']",
                           'payload__pull_request__base__user__id': "event_data['payload']['pull_request']['base']['user']['id']",
                           'payload__pull_request__base__user__node_id': "event_data['payload']['pull_request']['base']['user']['node_id']",
                           'payload__pull_request__base__user__type': "event_data['payload']['pull_request']['base']['user']['type']",
                           'payload__pull_request__base__repo__id': "event_data['payload']['pull_request']['base']['repo']['id']",
                           'payload__pull_request__base__repo__node_id': "event_data['payload']['pull_request']['base']['repo']['node_id']",
                           'payload__pull_request__base__repo__name': "event_data['payload']['pull_request']['base']['repo']['name']",
                           'payload__pull_request__base__repo__full_name': "event_data['payload']['pull_request']['base']['repo']['full_name']",
                           'payload__pull_request__base__repo__owner__login': "event_data['payload']['pull_request']['base']['repo']['owner']['login']",
                           'payload__pull_request__base__repo__owner__id': "event_data['payload']['pull_request']['base']['repo']['owner']['id']",
                           'payload__pull_request__base__repo__owner__node_id': "event_data['payload']['pull_request']['base']['repo']['owner']['node_id']",
                           'payload__pull_request__base__repo__owner__type': "event_data['payload']['pull_request']['base']['repo']['owner']['type']",
                           'payload__pull_request__base__repo__description': "event_data['payload']['pull_request']['base']['repo']['description']",
                           'payload__pull_request__base__repo__created_at': "event_data['payload']['pull_request']['base']['repo']['created_at']",
                           'payload__pull_request__base__repo__updated_at': "event_data['payload']['pull_request']['base']['repo']['updated_at']",
                           'payload__pull_request__base__repo__pushed_at': "event_data['payload']['pull_request']['base']['repo']['pushed_at']",
                           'payload__pull_request__base__repo__language': "event_data['payload']['pull_request']['base']['repo']['language']",
                           'payload__pull_request__base__repo__default_branch': "event_data['payload']['pull_request']['base']['repo']['default_branch']",
                           'payload__pull_request__author_association': "event_data['payload']['pull_request']['author_association']",
                           'payload__pull_request__mergeable_state': "event_data['payload']['pull_request']['mergeable_state']",
                           'payload__pull_request__merged_by__login': "event_data['payload']['pull_request']['merged_by']['login']",
                           'payload__pull_request__merged_by__id': "event_data['payload']['pull_request']['merged_by']['id']",
                           'payload__pull_request__merged_by__node_id': "event_data['payload']['pull_request']['merged_by']['node_id']",
                           'payload__pull_request__merged_by__type': "event_data['payload']['pull_request']['merged_by']['type']"},
    'fork_event': {'id': "event_data['id']",
                   'type': "event_data['type']",
                   'public': "event_data['public']",
                   'created_at': "event_data['created_at']",
                   'actor__id': "event_data['actor']['id']", 'actor__login': "event_data['actor']['login']",
                   'actor__display_login': "event_data['actor']['display_login']",
                   'repo__id': "event_data['repo']['id']", 'repo__name': "event_data['repo']['name']",
                   'payload__forkee__id': "event_data['payload']['forkee']['id']",
                   'payload__forkee__node_id': "event_data['payload']['forkee']['node_id']",
                   'payload__forkee__name': "event_data['payload']['forkee']['name']",
                   'payload__forkee__full_name': "event_data['payload']['forkee']['full_name']",
                   'payload__forkee__private': "event_data['payload']['forkee']['private']",
                   'payload__forkee__owner__login': "event_data['payload']['forkee']['owner']['login']",
                   'payload__forkee__owner__id': "event_data['payload']['forkee']['owner']['id']",
                   'payload__forkee__owner__node_id': "event_data['payload']['forkee']['owner']['node_id']",
                   'payload__forkee__owner__type': "event_data['payload']['forkee']['owner']['type']",
                   'payload__forkee__owner__site_admin': "event_data['payload']['forkee']['owner']['site_admin']",
                   'payload__forkee__description': "event_data['payload']['forkee']['description']",
                   'payload__forkee__created_at': "event_data['payload']['forkee']['created_at']",
                   'payload__forkee__updated_at': "event_data['payload']['forkee']['updated_at']",
                   'payload__forkee__pushed_at': "event_data['payload']['forkee']['pushed_at']",
                   'payload__forkee__default_branch': "event_data['payload']['forkee']['default_branch']",
                   'payload__forkee__public': "event_data['payload']['forkee']['public']"},
    'pull_request_review_event': {'id': "event_data['id']", 'type': "event_data['type']",
                                  'public': "event_data['public']",
                                  'created_at': "event_data['created_at']", 'actor__id': "event_data['actor']['id']",
                                  'actor__login': "event_data['actor']['login']",
                                  'actor__display_login': "event_data['actor']['display_login']",
                                  'repo__id': "event_data['repo']['id']", 'repo__name': "event_data['repo']['name']",
                                  'payload__action': "event_data['payload']['action']",
                                  'payload__review__id': "event_data['payload']['review']['id']",
                                  'payload__review__node_id': "event_data['payload']['review']['node_id']",
                                  'payload__review__user__login': "event_data['payload']['review']['user']['login']",
                                  'payload__review__user__id': "event_data['payload']['review']['user']['id']",
                                  'payload__review__user__node_id': "event_data['payload']['review']['user']['node_id']",
                                  'payload__review__user__type': "event_data['payload']['review']['user']['type']",
                                  'payload__review__body': "event_data['payload']['review']['body']",
                                  'payload__review__commit_id': "event_data['payload']['review']['commit_id']",
                                  'payload__review__submitted_at': "event_data['payload']['review']['submitted_at']",
                                  'payload__review__state': "event_data['payload']['review']['state']",
                                  'payload__review__author_association': "event_data['payload']['review']['author_association']",
                                  'payload__pull_request__id': "event_data['payload']['pull_request']['id']",
                                  'payload__pull_request__node_id': "event_data['payload']['pull_request']['node_id']",
                                  'payload__pull_request__number': "event_data['payload']['pull_request']['number']",
                                  'payload__pull_request__state': "event_data['payload']['pull_request']['state']",
                                  'payload__pull_request__title': "event_data['payload']['pull_request']['title']",
                                  'payload__pull_request__user__login': "event_data['payload']['pull_request']['user']['login']",
                                  'payload__pull_request__user__id': "event_data['payload']['pull_request']['user']['id']",
                                  'payload__pull_request__user__node_id': "event_data['payload']['pull_request']['user']['node_id']",
                                  'payload__pull_request__user__type': "event_data['payload']['pull_request']['user']['type']",
                                  'payload__pull_request__body': "event_data['payload']['pull_request']['body']",
                                  'payload__pull_request__created_at': "event_data['payload']['pull_request']['created_at']",
                                  'payload__pull_request__updated_at': "event_data['payload']['pull_request']['updated_at']",
                                  'payload__pull_request__closed_at': "event_data['payload']['pull_request']['closed_at']",
                                  'payload__pull_request__merged_at': "event_data['payload']['pull_request']['merged_at']",
                                  'payload__pull_request__merge_commit_sha': "event_data['payload']['pull_request']['merge_commit_sha']",
                                  'payload__pull_request__head__label': "event_data['payload']['pull_request']['head']['label']",
                                  'payload__pull_request__head__ref': "event_data['payload']['pull_request']['head']['ref']",
                                  'payload__pull_request__head__sha': "event_data['payload']['pull_request']['head']['sha']",
                                  'payload__pull_request__head__user__login': "event_data['payload']['pull_request']['head']['user']['login']",
                                  'payload__pull_request__head__user__id': "event_data['payload']['pull_request']['head']['user']['id']",
                                  'payload__pull_request__head__user__node_id': "event_data['payload']['pull_request']['head']['user']['node_id']",
                                  'payload__pull_request__head__user__type': "event_data['payload']['pull_request']['head']['user']['type']",
                                  'payload__pull_request__head__repo__id': "event_data['payload']['pull_request']['head']['repo']['id']",
                                  'payload__pull_request__head__repo__node_id': "event_data['payload']['pull_request']['head']['repo']['node_id']",
                                  'payload__pull_request__head__repo__name': "event_data['payload']['pull_request']['head']['repo']['name']",
                                  'payload__pull_request__head__repo__full_name': "event_data['payload']['pull_request']['head']['repo']['full_name']",
                                  'payload__pull_request__head__repo__owner__login': "event_data['payload']['pull_request']['head']['repo']['owner']['login']",
                                  'payload__pull_request__head__repo__owner__id': "event_data['payload']['pull_request']['head']['repo']['owner']['id']",
                                  'payload__pull_request__head__repo__owner__node_id': "event_data['payload']['pull_request']['head']['repo']['owner']['node_id']",
                                  'payload__pull_request__head__repo__owner__type': "event_data['payload']['pull_request']['head']['repo']['owner']['type']",
                                  'payload__pull_request__head__repo__created_at': "event_data['payload']['pull_request']['head']['repo']['created_at']",
                                  'payload__pull_request__head__repo__updated_at': "event_data['payload']['pull_request']['head']['repo']['updated_at']",
                                  'payload__pull_request__head__repo__pushed_at': "event_data['payload']['pull_request']['head']['repo']['pushed_at']",
                                  'payload__pull_request__head__repo__size': "event_data['payload']['pull_request']['head']['repo']['size']",
                                  'payload__pull_request__head__repo__language': "event_data['payload']['pull_request']['head']['repo']['language']",
                                  'payload__pull_request__head__repo__has_issues': "event_data['payload']['pull_request']['head']['repo']['has_issues']",
                                  'payload__pull_request__head__repo__has_projects': "event_data['payload']['pull_request']['head']['repo']['has_projects']",
                                  'payload__pull_request__head__repo__has_downloads': "event_data['payload']['pull_request']['head']['repo']['has_downloads']",
                                  'payload__pull_request__head__repo__open_issues_count': "event_data['payload']['pull_request']['head']['repo']['open_issues_count']",
                                  'payload__pull_request__head__repo__open_issues': "event_data['payload']['pull_request']['head']['repo']['open_issues']",
                                  'payload__pull_request__head__repo__default_branch': "event_data['payload']['pull_request']['head']['repo']['default_branch']",
                                  'payload__pull_request__base__label': "event_data['payload']['pull_request']['base']['label']",
                                  'payload__pull_request__base__ref': "event_data['payload']['pull_request']['base']['ref']",
                                  'payload__pull_request__base__sha': "event_data['payload']['pull_request']['base']['sha']",
                                  'payload__pull_request__base__user__login': "event_data['payload']['pull_request']['base']['user']['login']",
                                  'payload__pull_request__base__user__id': "event_data['payload']['pull_request']['base']['user']['id']",
                                  'payload__pull_request__base__user__node_id': "event_data['payload']['pull_request']['base']['user']['node_id']",
                                  'payload__pull_request__base__user__type': "event_data['payload']['pull_request']['base']['user']['type']",
                                  'payload__pull_request__base__repo__id': "event_data['payload']['pull_request']['base']['repo']['id']",
                                  'payload__pull_request__base__repo__node_id': "event_data['payload']['pull_request']['base']['repo']['node_id']",
                                  'payload__pull_request__base__repo__name': "event_data['payload']['pull_request']['base']['repo']['name']",
                                  'payload__pull_request__base__repo__full_name': "event_data['payload']['pull_request']['base']['repo']['full_name']",
                                  'payload__pull_request__base__repo__owner__login': "event_data['payload']['pull_request']['base']['repo']['owner']['login']",
                                  'payload__pull_request__base__repo__owner__id': "event_data['payload']['pull_request']['base']['repo']['owner']['id']",
                                  'payload__pull_request__base__repo__owner__node_id': "event_data['payload']['pull_request']['base']['repo']['owner']['node_id']",
                                  'payload__pull_request__base__repo__owner__type': "event_data['payload']['pull_request']['base']['repo']['owner']['type']",
                                  'payload__pull_request__base__repo__created_at': "event_data['payload']['pull_request']['base']['repo']['created_at']",
                                  'payload__pull_request__base__repo__updated_at': "event_data['payload']['pull_request']['base']['repo']['updated_at']",
                                  'payload__pull_request__base__repo__pushed_at': "event_data['payload']['pull_request']['base']['repo']['pushed_at']",
                                  'payload__pull_request__base__repo__size': "event_data['payload']['pull_request']['base']['repo']['size']",
                                  'payload__pull_request__base__repo__language': "event_data['payload']['pull_request']['base']['repo']['language']",
                                  'payload__pull_request__base__repo__has_issues': "event_data['payload']['pull_request']['base']['repo']['has_issues']",
                                  'payload__pull_request__base__repo__has_projects': "event_data['payload']['pull_request']['base']['repo']['has_projects']",
                                  'payload__pull_request__base__repo__has_downloads': "event_data['payload']['pull_request']['base']['repo']['has_downloads']",
                                  'payload__pull_request__base__repo__open_issues_count': "event_data['payload']['pull_request']['base']['repo']['open_issues_count']",
                                  'payload__pull_request__base__repo__open_issues': "event_data['payload']['pull_request']['base']['repo']['open_issues']",
                                  'payload__pull_request__base__repo__default_branch': "event_data['payload']['pull_request']['base']['repo']['default_branch']",
                                  'payload__pull_request__author_association': "event_data['payload']['pull_request']['author_association']"},
    'push_event': {'id': "event_data['id']", 'type': "event_data['type']", 'public': "event_data['public']",
                   'created_at': "event_data['created_at']", 'actor__id': "event_data['actor']['id']",
                   'actor__login': "event_data['actor']['login']",
                   'actor__display_login': "event_data['actor']['display_login']",
                   'actor__gravatar_id': "event_data['actor']['gravatar_id']",
                   'actor__url': "event_data['actor']['url']", 'repo__id': "event_data['repo']['id']",
                   'repo__name': "event_data['repo']['name']", 'repo__url': "event_data['repo']['url']",
                   'payload__push_id': "event_data['payload']['push_id']",
                   'payload__size': "event_data['payload']['size']",
                   'payload__distinct_size': "event_data['payload']['distinct_size']",
                   'payload__ref': "event_data['payload']['ref']", 'payload__head': "event_data['payload']['head']",
                   'payload__before': "event_data['payload']['before']",
                   'payload__commits': "event_data['payload']['commits']"},
    'commit_comment_event': {
        "id": "event_data['id']",
        "type": "event_data['type']",
        "public": "event_data['public']",
        "created_at": "event_data['created_at']",
        "actor__id": "event_data['actor']['id']",
        "actor__login": "event_data['actor']['login']",
        "actor__display_login": "event_data['actor']['display_login']",
        "repo__id": "event_data['repo']['id']",
        "repo__name": "event_data['repo']['name']",
        "payload__comment__id": "event_data['payload']['comment']['id']",
        "payload__comment__node_id": "event_data['payload']['comment']['node_id']",
        "payload__comment__user__login": "event_data['payload']['comment']['user']['login']",
        "payload__comment__user__id": "event_data['payload']['comment']['user']['id']",
        "payload__comment__user__node_id": "event_data['payload']['comment']['user']['node_id']",
        "payload__comment__user__type": "event_data['payload']['comment']['user']['type']",
        "payload__comment__path": "event_data['payload']['comment']['path']",
        "payload__comment__commit_id": "event_data['payload']['comment']['commit_id']",
        "payload__comment__created_at": "event_data['payload']['comment']['created_at']",
        "payload__comment__updated_at": "event_data['payload']['comment']['updated_at']",
        "payload__comment__author_association": "event_data['payload']['comment']['author_association']",
        "payload__comment__body": "event_data['payload']['comment']['body']"
    }

    ,
    'issues_event': {'id': "event_data['id']", 'type': "event_data['type']", 'public': "event_data['public']",
                     'created_at': "event_data['created_at']", 'actor__id': "event_data['actor']['id']",
                     'actor__login': "event_data['actor']['login']",
                     'actor__display_login': "event_data['actor']['display_login']",
                     'repo__id': "event_data['repo']['id']", 'repo__name': "event_data['repo']['name']",
                     'payload__action': "event_data['payload']['action']",
                     'payload__issue__id': "event_data['payload']['issue']['id']",
                     'payload__issue__node_id': "event_data['payload']['issue']['node_id']",
                     'payload__issue__number': "event_data['payload']['issue']['number']",
                     'payload__issue__title': "event_data['payload']['issue']['title']",
                     'payload__issue__user__login': "event_data['payload']['issue']['user']['login']",
                     'payload__issue__user__id': "event_data['payload']['issue']['user']['id']",
                     'payload__issue__user__node_id': "event_data['payload']['issue']['user']['node_id']",
                     'payload__issue__user__type': "event_data['payload']['issue']['user']['type']",
                     'payload__issue__state': "event_data['payload']['issue']['state']",
                     'payload__issue__assignee__login': "event_data['payload']['issue']['assignee']['login']",
                     'payload__issue__assignee__id': "event_data['payload']['issue']['assignee']['id']",
                     'payload__issue__assignee__node_id': "event_data['payload']['issue']['assignee']['node_id']",
                     'payload__issue__assignee__type': "event_data['payload']['issue']['assignee']['type']",
                     'payload__issue__created_at': "event_data['payload']['issue']['created_at']",
                     'payload__issue__updated_at': "event_data['payload']['issue']['updated_at']",
                     'payload__issue__closed_at': "event_data['payload']['issue']['closed_at']",
                     'payload__issue__author_association': "event_data['payload']['issue']['author_association']",
                     'payload__issue__active_lock_reason': "event_data['payload']['issue']['active_lock_reason']",
                     'payload__issue__body': "event_data['payload']['issue']['body']",
                     'org__id': "event_data['org']['id']", 'org__login': "event_data['org']['login']"}
    ,
    'watch_event': {"id": "event_data['id']", "type": "event_data['type']", "public": "event_data['public']",
                    "created_at": "event_data['created_at']", "actor__id": "event_data['actor']['id']",
                    "actor__login": "event_data['actor']['login']",
                    "actor__display_login": "event_data['actor']['display_login']",
                    "actor__url": "event_data['actor']['url']",
                    "actor__avatar_url": "event_data['actor']['avatar_url']", "repo__id": "event_data['repo']['id']",
                    "repo__name": "event_data['repo']['name']", "repo__url": "event_data['repo']['url']",
                    "payload__action": "event_data['payload']['action']"}

}
